version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csi_ml_service
    ports:
      - "8001:8080"
    volumes:
      - ./models_bin:/app/models_bin
    env_file:
      - .env
    networks:
      - csi_network
    restart: always

networks:
  csi_network:
    driver: bridge
